hp = 100;
maxhp = hp;
mp = 20;
maxmp = mp;
str = 2;
def = 2;
buff = status.none;
debuff = status.none;
portrait = s_testportrait;
textboxspr = s_9sliceselect;
textboxsprhover = s_9slice;
name = "Test Player 1";
selection = "none";
target = "none";
turndone = false;
wepequipped = s_swordicon;
show_debug_message(string(id));
show_debug_message("Hello?");